### ISSUE TITLE
recipeCommand throws error when searching for a specific value

### ISSUE THREAD

**Issue by S1mplyD** [S1mplyD/RecipeBotReborn#22]
CombinedError (2)
  Received one or more errors

  1 ValidationError > s.nullish
  |   Expected undefined or null
  | 
  |   Received:
  |   | ''

  2 ExpectedConstraintError > s.string.url
  |   Invalid URL
  | 
  |   Expected: expected to match a URL
  | 
  |   Received:
  |   | ''

    at UnionValidator.handle (/home/luca/Documents/GitHub/RecipeBot2.0/node_modules/@sapphire/shapeshift/src/validators/UnionValidator.ts:105:14)
    at UnionValidator.parse (/home/luca/Documents/GitHub/RecipeBot2.0/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
    at EmbedBuilder.setImage (/home/luca/Documents/GitHub/RecipeBot2.0/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:254:21)
    at Object.<anonymous> (/home/luca/Documents/GitHub/RecipeBot2.0/src/commands/common/recipeCommand.ts:124:14)
    at Generator.next (<anonymous>)
    at fulfilled (/home/luca/Documents/GitHub/RecipeBot2.0/src/commands/common/recipeCommand.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by S1mplyD** [comment]
Fixed in commit 4840d6fa69f119be1f8208effdedc5121a61310a
