### ISSUE TITLE
List all categories error

### ISSUE THREAD

**Issue by S1mplyD** [S1mplyD/RecipeBotReborn#31]
```
CombinedError (2)
  Received one or more errors

  1 ExpectedValidationError > s.literal(V)
  |   Expected values to be equals
  | 
  |   Expected:
  |   | null
  | 
  |   Received:
  |   | "1) Air Fryer\n2) Allrecipes Allstar\n3) Antipasti\n4) Appetizers\n5) Apple Pie\n6) Applesauce\n7) Artichoke Dips\n8) Bagels\n9) Baked Beans\n10) Beef Stroganoff\n11) Biscotti\n12) Biscuits\n13) Blintzes\n14) Blondies\n15) Bloody Marys\n16) Blueberry Pie\n17) Borscht\n18) Breads\n19) Breakfast Potatoes\n20) Breakfast Stratas\n21) Breakfast and Brunch\n22) Brines\n23) Brownies\n24) Bruschetta\n25) Buffalo Chicken Dips\n26) Buffalo Chicken Wings\n27) Bulgogi\n28) Burgers\n29) Burritos\n30) Cabbage Rolls\n31) Cakes\n32) Calzones\n33) Camping\n34) Canning and Preserving\n35) Casseroles\n36) Ceviche\n37) Cheese Balls\n38) Cheese Fondue\n39) Cheesecakes\n40) Chef John\n41) Cherry Pie\n42) Chess Pie\n43) Chicken Adobo\n44) Chicken Cacciatore\n45) Chicken Cordon Bleu\n46) Chicken Marsala\n47) Chicken Parmesan\n48) Chicken Piccata\n49) Chicken Teriyaki\n50) Chilaquiles\n51) Chiles Rellenos\n52) Chili\n53) Chowders\n54) Christmas\n55) Cinnamon Rolls\n56) Cobblers\n57) Cocktails\n58) Coleslaws\n59) Comfort Food\n60) Cookies\n61) Cooking for One\n62) Cooking for Two\n63) Cooking for a Crowd\n64) Copycat\n65) Cornbread\n66) Corned Beef\n67) Crackers\n68) Creme Brulee\n69) Crisps and Crumbles\n70) Cupcakes\n71) Danishes\n72) Desserts\n73) Deviled Eggs\n74) Diabetic\n75) Dinner\n76) Divinity\n77) Diwali\n78) Doughnuts\n79) Drinks\n80) Dumplings\n81) Easter\n82) Egg Rolls\n83) Eggnog\n84) Eggplant Parmesan\n85) Empanadas\n86) Enchiladas\n87) Energy Balls\n88) Etouffee\n89) Fajitas\n90) Falafel\n91) Father's Day\n92) Fettuccini\n93) Filet Mignon\n94) First Courses\n95) Flan\n96) Flat Iron Steak\n97) Flatbreads\n98) Fondant\n99) Food Gifts\n100) French Toast\n101) Fried Chicken\n102) Fried Rice\n103) Fries\n104) Frittatas\n105) Frostings and Icings\n106) Fruitcakes\n107) Fudge\n108) Garlic Bread\n109) Gazpacho\n110) Gingersnaps\n111) Gluten-Free\n112) Gnocchi\n113) Goulash\n114) Granola\n115) Gravies\n116) Grits\n117) Ground Lamb\n118) Guacamole\n119) Gumbos\n120) Gyros\n121) Halloween\n122) Hanukkah\n123) Hawaiian\n124) Healthy\n125) High Fiber\n126) Homemade Pasta\n127) Hummus\n128) Hushpuppies\n129) Ice Cream\n130) Instant Pot\n131) Irish Soda Bread\n132) Jalapeno Poppers\n133) Jambalayas\n134) Jams and Jellies\n135) Jams and Preserves\n136) Jell-O Shots\n137) Jerky\n138) July 4th\n139) Keto\n140) Key Lime Pie\n141) Kolache\n142) Kosher\n143) Kwanzaa\n144) Labor Day\n145) Lasagna\n146) Leavened products\n147) Leftovers\n148) Lemon Bars\n149) Lemonade\n150) Lent\n151) Lettuce Wraps\n152) Linguine\n153) Low Calorie\n154) Low Cholesterol\n155) Low Fat\n156) Low Glycemic Impact\n157) Low Sodium\n158) Lunar New Year\n159) Lunch\n160) Macaroni and Cheese\n161) Macaroons\n162) Main Courses\n163) Main Dishes\n164) Make-Ahead\n165) Manicotti\n166) Mardi Gras\n167) Margaritas\n168) Mashed Potatoes\n169) Meal Prep\n170) Meatballs\n171) Meatloaf\n172) Mediterranean Diet\n173) Mexican\n174) Mincemeat Pie\n175) Mojitos\n176) Monkey Bread\n177) Mother's Day\n178) Mousses\n179) Muffins\n180) Nachos\n181) New Year's\n182) Oatmeal\n183) Omelets\n184) Overnight Oats\n185) Pad Thai\n186) Paella\n187) Paleo\n188) Pancakes\n189) Pancit\n190) Panini\n191) Passover\n192) Pasta Carbonara\n193) Pasta Primavera\n194) Pasties\n195) Pastries\n196) Pate\n197) Pavlovas\n198) Pecan Pie\n199) Pestos\n200) Pet Food\n201) Pickles\n202) Picnic\n203) Pie Crusts\n204) Pierogies\n205) Pies\n206) Pizza\n207) Polenta\n208) Popcorn\n209) Popovers and Yorkshire Puddings\n210) Pork\n211) Pot Roast\n212) Potluck\n213) Pretzels\n214) Pumpkin Pie\n215) Pumpkin Seeds\n216) Punch\n217) Purim\n218) Quesadillas\n219) Quiches\n220) Quick and Easy\n221) Ramadan\n222) Ravioli\n223) Raw Food Diet\n224) Refried Beans\n225) Relishes\n226) Rhubarb Pie\n227) Rice Pilaf\n228) Rice Puddings\n229) Risotto\n230) Road Trip Snacks\n231) Roasts\n232) Rosh Hashanah\n233) Salad Dressings\n234) Salads\n235) Salisbury Steak\n236) Salmon\n237) Salsas\n238) Sandwiches\n239) Sangrias\n240) Sauces\n241) Savory tarts\n242) Scones\n243) Seder\n244) Seitan\n245) Shepherd's Pie\n246) Shortbread\n247) Shortcakes\n248) Shrimp Scampi\n249) Side Dishes\n250) Single Courses\n251) Slab Pie\n252) Sliders\n253) Sloppy Joes\n254) Slow Cooker\n255) Smoothies\n256) Snickerdoodles\n257) Soups\n258) Sous Vide\n259) Spaghetti\n260) Spanish Rice\n261) Spinach Dips\n262) St. Patrick's Day\n263) Stews\n264) Strawberry Pie\n265) Stuffed Mushrooms\n266) Stuffed Peppers\n267) Sugar-Free\n268) Sushi\n269) Sweet Potato Pie\n270) Sweets and desserts\n271) Swiss Steak\n272) TVP\n273) Tacos\n274) Tailgating\n275) Tamales\n276) Tapas\n277) Tempeh\n278) Tetrazzini\n279) Thanksgiving\n280) Tiramisu\n281) Toffee\n282) Tofu\n283) Tortellini\n284) Tortes\n285) Tortillas\n286) Tostadas\n287) Truffles\n288) Valentine's Day\n289) Vegan\n290) Vegetables A to Z\n291) Vegetarian\n292) Waffles\n293) Whole30\n294) Winter Squash\n295) Yams\n296) Ziti\n"

  2 ExpectedConstraintError > s.string.lengthLessThanOrEqual
  |   Invalid string length
  | 
  |   Expected: expected.length <= 4096
  | 
  |   Received:
  |   | "1) Air Fryer\n2) Allrecipes Allstar\n3) Antipasti\n4) Appetizers\n5) Apple Pie\n6) Applesauce\n7) Artichoke Dips\n8) Bagels\n9) Baked Beans\n10) Beef Stroganoff\n11) Biscotti\n12) Biscuits\n13) Blintzes\n14) Blondies\n15) Bloody Marys\n16) Blueberry Pie\n17) Borscht\n18) Breads\n19) Breakfast Potatoes\n20) Breakfast Stratas\n21) Breakfast and Brunch\n22) Brines\n23) Brownies\n24) Bruschetta\n25) Buffalo Chicken Dips\n26) Buffalo Chicken Wings\n27) Bulgogi\n28) Burgers\n29) Burritos\n30) Cabbage Rolls\n31) Cakes\n32) Calzones\n33) Camping\n34) Canning and Preserving\n35) Casseroles\n36) Ceviche\n37) Cheese Balls\n38) Cheese Fondue\n39) Cheesecakes\n40) Chef John\n41) Cherry Pie\n42) Chess Pie\n43) Chicken Adobo\n44) Chicken Cacciatore\n45) Chicken Cordon Bleu\n46) Chicken Marsala\n47) Chicken Parmesan\n48) Chicken Piccata\n49) Chicken Teriyaki\n50) Chilaquiles\n51) Chiles Rellenos\n52) Chili\n53) Chowders\n54) Christmas\n55) Cinnamon Rolls\n56) Cobblers\n57) Cocktails\n58) Coleslaws\n59) Comfort Food\n60) Cookies\n61) Cooking for One\n62) Cooking for Two\n63) Cooking for a Crowd\n64) Copycat\n65) Cornbread\n66) Corned Beef\n67) Crackers\n68) Creme Brulee\n69) Crisps and Crumbles\n70) Cupcakes\n71) Danishes\n72) Desserts\n73) Deviled Eggs\n74) Diabetic\n75) Dinner\n76) Divinity\n77) Diwali\n78) Doughnuts\n79) Drinks\n80) Dumplings\n81) Easter\n82) Egg Rolls\n83) Eggnog\n84) Eggplant Parmesan\n85) Empanadas\n86) Enchiladas\n87) Energy Balls\n88) Etouffee\n89) Fajitas\n90) Falafel\n91) Father's Day\n92) Fettuccini\n93) Filet Mignon\n94) First Courses\n95) Flan\n96) Flat Iron Steak\n97) Flatbreads\n98) Fondant\n99) Food Gifts\n100) French Toast\n101) Fried Chicken\n102) Fried Rice\n103) Fries\n104) Frittatas\n105) Frostings and Icings\n106) Fruitcakes\n107) Fudge\n108) Garlic Bread\n109) Gazpacho\n110) Gingersnaps\n111) Gluten-Free\n112) Gnocchi\n113) Goulash\n114) Granola\n115) Gravies\n116) Grits\n117) Ground Lamb\n118) Guacamole\n119) Gumbos\n120) Gyros\n121) Halloween\n122) Hanukkah\n123) Hawaiian\n124) Healthy\n125) High Fiber\n126) Homemade Pasta\n127) Hummus\n128) Hushpuppies\n129) Ice Cream\n130) Instant Pot\n131) Irish Soda Bread\n132) Jalapeno Poppers\n133) Jambalayas\n134) Jams and Jellies\n135) Jams and Preserves\n136) Jell-O Shots\n137) Jerky\n138) July 4th\n139) Keto\n140) Key Lime Pie\n141) Kolache\n142) Kosher\n143) Kwanzaa\n144) Labor Day\n145) Lasagna\n146) Leavened products\n147) Leftovers\n148) Lemon Bars\n149) Lemonade\n150) Lent\n151) Lettuce Wraps\n152) Linguine\n153) Low Calorie\n154) Low Cholesterol\n155) Low Fat\n156) Low Glycemic Impact\n157) Low Sodium\n158) Lunar New Year\n159) Lunch\n160) Macaroni and Cheese\n161) Macaroons\n162) Main Courses\n163) Main Dishes\n164) Make-Ahead\n165) Manicotti\n166) Mardi Gras\n167) Margaritas\n168) Mashed Potatoes\n169) Meal Prep\n170) Meatballs\n171) Meatloaf\n172) Mediterranean Diet\n173) Mexican\n174) Mincemeat Pie\n175) Mojitos\n176) Monkey Bread\n177) Mother's Day\n178) Mousses\n179) Muffins\n180) Nachos\n181) New Year's\n182) Oatmeal\n183) Omelets\n184) Overnight Oats\n185) Pad Thai\n186) Paella\n187) Paleo\n188) Pancakes\n189) Pancit\n190) Panini\n191) Passover\n192) Pasta Carbonara\n193) Pasta Primavera\n194) Pasties\n195) Pastries\n196) Pate\n197) Pavlovas\n198) Pecan Pie\n199) Pestos\n200) Pet Food\n201) Pickles\n202) Picnic\n203) Pie Crusts\n204) Pierogies\n205) Pies\n206) Pizza\n207) Polenta\n208) Popcorn\n209) Popovers and Yorkshire Puddings\n210) Pork\n211) Pot Roast\n212) Potluck\n213) Pretzels\n214) Pumpkin Pie\n215) Pumpkin Seeds\n216) Punch\n217) Purim\n218) Quesadillas\n219) Quiches\n220) Quick and Easy\n221) Ramadan\n222) Ravioli\n223) Raw Food Diet\n224) Refried Beans\n225) Relishes\n226) Rhubarb Pie\n227) Rice Pilaf\n228) Rice Puddings\n229) Risotto\n230) Road Trip Snacks\n231) Roasts\n232) Rosh Hashanah\n233) Salad Dressings\n234) Salads\n235) Salisbury Steak\n236) Salmon\n237) Salsas\n238) Sandwiches\n239) Sangrias\n240) Sauces\n241) Savory tarts\n242) Scones\n243) Seder\n244) Seitan\n245) Shepherd's Pie\n246) Shortbread\n247) Shortcakes\n248) Shrimp Scampi\n249) Side Dishes\n250) Single Courses\n251) Slab Pie\n252) Sliders\n253) Sloppy Joes\n254) Slow Cooker\n255) Smoothies\n256) Snickerdoodles\n257) Soups\n258) Sous Vide\n259) Spaghetti\n260) Spanish Rice\n261) Spinach Dips\n262) St. Patrick's Day\n263) Stews\n264) Strawberry Pie\n265) Stuffed Mushrooms\n266) Stuffed Peppers\n267) Sugar-Free\n268) Sushi\n269) Sweet Potato Pie\n270) Sweets and desserts\n271) Swiss Steak\n272) TVP\n273) Tacos\n274) Tailgating\n275) Tamales\n276) Tapas\n277) Tempeh\n278) Tetrazzini\n279) Thanksgiving\n280) Tiramisu\n281) Toffee\n282) Tofu\n283) Tortellini\n284) Tortes\n285) Tortillas\n286) Tostadas\n287) Truffles\n288) Valentine's Day\n289) Vegan\n290) Vegetables A to Z\n291) Vegetarian\n292) Waffles\n293) Whole30\n294) Winter Squash\n295) Yams\n296) Ziti\n"

    at UnionValidator.handle (/home/luca/Documents/GitHub/RecipeBot2.0/node_modules/@sapphire/shapeshift/src/validators/UnionValidator.ts:105:14)
    at UnionValidator.parse (/home/luca/Documents/GitHub/RecipeBot2.0/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
    at EmbedBuilder.setDescription (/home/luca/Documents/GitHub/RecipeBot2.0/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:223:24)
    at Object.<anonymous> (/home/luca/Documents/GitHub/RecipeBot2.0/src/commands/common/listCommand.ts:42:12)
    at Generator.next (<anonymous>)
    at fulfilled (/home/luca/Documents/GitHub/RecipeBot2.0/src/commands/common/listCommand.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by S1mplyD** [comment]
fix in commit 15387f9
